# -*- coding: utf-8 -*-
"""V2 UAV WILDFIRES

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11CaMCt49ZGO-e4afAkJYPg1ZLoBMX8V-
"""

# -*- coding: utf-8 -*-
"""UAV Wildfire Patrol Q-Learning V1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16nHwpmnYFfwt07be7A-LPAO2Cb3es0tQ
"""

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# pip install gymnasium

import gymnasium as gym
from gymnasium import spaces
import numpy as np
import math
import random
import matplotlib
import matplotlib.pyplot as plt
from collections import namedtuple, deque
from itertools import count
from matplotlib.path import Path
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F

# set up matplotlib
# %matplotlib inline
is_ipython = 'inline' in matplotlib.get_backend()
if is_ipython:
    from IPython import display

plt.ion()

# if GPU is to be used
device = torch.device(
    "cuda" if torch.cuda.is_available() else
    "mps" if torch.backends.mps.is_available() else
    "cpu"
)

class AreaDiscoveryEnv(gym.Env):
    def __init__(self):
        super().__init__()
        self.action_space = spaces.Discrete(9)

        # Real-world scaled observation bounds:
        # X: -250 to 250, Y: -100 to 100, steps, battery, temperature (0-100)
        self.observation_space = spaces.Box(
            low=np.array([-250.0, -100.0, 0, 0.0, 0.0]),
            high=np.array([250.0, 100.0, 35, 100.0, 100.0]),
            dtype=np.float32
        )

        self.max_steps = 35
        self.grid_x = 250
        self.grid_y = 100

        # Ranger Stations: Index 0 is Main Home Center, Indices 1-3 are new stations
        self.stations = [
            np.array([135.0, 45.0], dtype=np.float32),  # Main Home Center Station
            np.array([120.0, 62.0], dtype=np.float32),  # New Station 1
            np.array([150.0, 60.0], dtype=np.float32),  # New Station 2
            np.array([150.0, 20.0], dtype=np.float32)   # New Station 3
        ]

        # Drone starts at the main home center station (index 0)
        self.start_pos = self.stations[0]

        # Discovery radius scaled to real life (~0.32 miles / ~1,700 ft per step scan width)
        self.discovery_radius = 2

        # Topographical Trace of the Santa Monica Mountains
        mountain_coords = [
            (3.0, 48.0), (3.6, 49.1), (4.2, 50.1), (4.8, 51.1), (5.5, 52.0), (6.2, 52.8),
            (7.0, 53.5), (7.9, 54.1), (8.8, 54.6), (9.6, 54.9), (10.5, 55.2), (11.5, 55.5),
            (12.5, 55.8), (13.3, 56.1), (14.2, 56.4), (15.1, 56.6), (16.0, 56.8), (17.2, 57.2),
            (18.5, 57.7), (19.5, 58.2), (20.5, 58.8), (21.5, 59.3), (22.5, 59.7), (23.5, 60.1),
            (24.5, 60.4), (25.5, 60.8), (26.5, 61.2), (27.5, 61.6), (28.5, 62.0), (29.5, 62.4),
            (30.5, 62.8), (31.2, 63.3), (32.0, 63.8), (32.9, 64.4), (33.8, 64.9), (34.6, 65.3),
            (35.5, 65.6), (36.3, 66.0), (37.2, 66.4), (38.1, 66.8), (39.0, 67.2), (40.0, 67.6),
            (41.0, 67.9), (42.0, 68.4), (43.0, 68.8), (44.0, 69.2), (45.0, 69.5), (46.2, 69.8),
            (47.5, 70.1), (48.5, 70.4), (49.5, 70.6), (50.6, 70.8), (51.8, 71.0), (52.9, 71.2),
            (54.0, 71.4), (55.2, 71.6), (56.5, 71.7), (57.8, 71.9), (59.0, 72.0), (60.2, 71.9),
            (61.5, 71.8), (62.8, 71.6), (64.0, 71.4), (65.2, 71.2), (66.5, 71.1), (67.5, 70.9),
            (68.5, 70.8), (69.5, 70.5), (70.5, 70.2), (71.8, 69.9), (73.0, 69.6), (74.2, 69.2),
            (75.5, 68.8), (76.6, 68.3), (77.8, 67.7), (78.9, 67.1), (80.0, 66.5), (81.1, 65.8),
            (82.2, 65.2), (83.3, 64.7), (84.5, 64.3), (85.6, 64.0), (86.8, 63.8), (87.9, 63.5),
            (89.0, 63.2), (90.0, 62.5), (91.0, 61.8), (92.0, 61.3), (93.0, 60.8), (94.2, 60.5),
            (95.5, 60.2), (96.8, 59.8), (98.0, 59.5), (99.2, 59.2), (100.5, 59.0), (101.8, 58.9),
            (103.0, 59.0), (104.2, 59.1), (105.5, 59.3), (106.8, 59.6), (108.0, 60.0), (109.0, 60.4),
            (110.0, 60.9), (111.2, 61.3), (112.5, 61.8), (113.8, 62.5), (115.0, 63.2), (116.2, 63.9),
            (117.5, 64.5), (118.8, 65.2), (120.0, 66.0), (121.2, 66.9), (122.5, 67.8), (123.8, 68.6),
            (125.0, 69.5), (126.2, 70.4), (127.5, 71.4), (128.8, 72.3), (130.0, 73.2), (131.2, 74.4),
            (132.5, 75.5), (133.2, 76.8), (134.0, 78.0), (134.6, 79.5), (135.2, 81.0), (135.8, 82.8),
            (136.4, 84.5), (137.0, 86.2), (137.5, 87.8), (138.2, 89.4), (138.8, 91.0), (139.4, 92.5),
            (140.0, 94.0), (140.8, 95.3), (141.5, 96.5), (142.2, 97.4), (143.0, 98.2), (143.8, 98.8),
            (144.5, 99.0), (145.0, 99.2), (145.5, 99.0), (146.0, 98.7), (146.5, 98.2), (147.2, 97.2),
            (147.8, 96.0), (148.4, 94.5), (149.0, 93.0), (149.6, 91.2), (150.2, 89.5), (150.8, 87.8),
            (151.5, 86.0), (152.2, 84.2), (153.0, 82.5), (153.8, 80.8), (154.5, 79.0), (155.2, 77.8),
            (156.0, 76.5), (156.8, 75.8), (157.5, 75.0), (158.5, 74.2), (159.5, 73.5), (160.5, 72.8),
            (161.5, 72.0), (162.8, 71.1), (164.0, 70.2), (165.2, 69.2), (166.5, 68.2), (167.8, 67.1),
            (169.0, 66.0), (170.2, 65.2), (171.5, 64.5), (172.8, 64.0), (174.0, 63.5), (175.2, 63.1),
            (176.5, 62.8), (177.8, 62.5), (179.0, 62.2), (180.5, 62.0), (182.0, 61.8), (183.8, 61.6),
            (185.5, 61.5), (187.2, 61.3), (189.0, 61.0), (191.0, 60.8), (193.0, 60.6), (195.0, 60.4),
            (197.0, 60.2), (199.0, 60.0), (201.0, 59.8), (203.0, 59.6), (205.0, 59.4), (207.0, 59.2),
            (209.0, 59.0), (211.0, 58.8), (213.0, 58.6), (215.0, 58.4), (217.0, 58.2), (219.0, 57.9),
            (221.0, 57.6), (223.0, 57.3), (225.0, 56.8), (227.0, 56.3), (229.0, 55.6), (231.0, 54.8),
            (233.0, 54.0), (235.0, 53.0), (237.0, 52.0), (239.0, 50.8), (241.0, 49.5), (242.8, 48.0),
            (244.5, 46.5), (245.8, 44.8), (247.0, 43.0), (248.0, 41.0), (248.8, 39.0), (249.4, 37.0),
            (249.8, 35.0), (249.5, 33.0), (249.0, 31.0), (248.3, 29.0), (247.5, 27.0), (246.5, 25.0),
            (245.5, 23.0), (244.4, 21.2), (243.2, 19.5), (241.9, 17.9), (240.5, 16.5), (239.2, 15.1),
            (238.0, 13.8), (236.9, 12.6), (235.8, 11.5), (234.9, 10.6), (234.0, 9.8), (233.0, 9.1),
            (232.0, 8.5), (231.0, 8.2), (230.0, 8.0), (229.0, 8.3), (228.0, 8.8), (227.0, 9.3),
            (226.0, 9.8), (224.8, 10.2), (223.5, 10.6), (221.8, 11.0), (220.0, 11.4), (218.0, 11.8),
            (216.0, 12.2), (214.0, 12.5), (212.0, 12.8), (210.0, 13.1), (208.0, 13.3), (206.0, 13.5),
            (204.0, 13.7), (201.8, 13.9), (199.5, 14.1), (197.2, 14.3), (195.0, 14.5), (192.5, 14.7),
            (190.0, 14.8), (187.5, 14.9), (185.0, 14.9), (182.5, 14.8), (180.0, 14.7), (177.5, 14.5),
            (175.0, 14.3), (172.5, 14.1), (170.0, 13.9), (167.5, 13.7), (165.0, 13.6), (162.5, 13.4),
            (160.0, 13.2), (157.5, 12.9), (155.0, 12.7), (152.5, 12.5), (150.0, 12.2), (148.8, 11.9),
            (147.5, 11.5), (146.2, 10.9), (145.0, 10.2), (144.0, 9.4), (143.0, 8.5), (142.1, 7.5),
            (141.2, 6.5), (140.3, 5.5), (139.5, 4.5), (138.6, 3.6), (137.8, 2.8), (136.9, 2.1),
            (136.0, 1.5), (135.0, 1.0), (134.0, 0.6), (133.0, 0.3), (132.0, 0.2), (131.0, 0.3),
            (130.0, 0.5), (129.0, 0.8), (128.0, 1.2), (127.0, 1.8), (126.0, 2.4), (125.0, 3.2),
            (124.0, 4.0), (123.1, 4.9), (122.2, 5.8), (121.3, 6.8), (120.5, 7.8), (119.6, 8.7),
            (118.8, 9.6), (117.9, 10.3), (117.0, 11.0), (116.0, 11.4), (115.0, 11.8), (113.8, 12.0),
            (112.5, 12.2), (111.0, 12.5), (109.5, 12.8), (107.8, 13.1), (106.0, 13.5), (104.2, 13.8),
            (102.5, 14.2), (100.5, 14.6), (98.5, 15.0), (96.5, 15.4), (94.5, 15.8), (92.5, 16.3),
            (90.5, 16.7), (88.5, 17.1), (86.5, 17.6), (84.5, 18.0), (82.5, 18.5), (80.5, 19.0),
            (78.5, 19.5), (76.2, 20.1), (74.0, 20.6), (71.8, 21.2), (69.5, 21.8), (67.2, 22.5),
            (65.0, 23.2), (62.8, 23.9), (60.5, 24.6), (58.2, 25.4), (56.0, 26.2), (53.8, 27.1),
            (51.5, 28.0), (49.5, 28.9), (47.5, 29.8), (45.5, 30.8), (43.5, 31.8), (41.5, 32.9),
            (39.5, 34.0), (37.5, 35.2), (35.5, 36.4), (33.5, 37.6), (31.5, 38.8), (29.5, 40.0),
            (27.5, 41.2), (25.5, 42.4), (23.5, 43.4), (21.5, 44.4), (19.5, 45.2), (17.5, 45.9),
            (15.5, 46.5), (13.5, 47.0), (11.5, 47.4), (9.8, 47.6), (8.0, 47.8), (5.5, 47.9),
            (3.0, 48.0)
        ]
        self.boundary_path = Path(mountain_coords)

        # Full map mask spanning 250x100
        self.valid_mask = np.zeros((self.grid_x, self.grid_y), dtype=bool)
        for i in range(self.grid_x):
            for j in range(self.grid_y):
                if self.boundary_path.contains_point((i, j)):
                    self.valid_mask[i, j] = True

        self.temperature_grid = np.zeros((self.grid_x, self.grid_y), dtype=np.float32)
        self.fire_pos = np.array([0.0, 0.0], dtype=np.float32)
        self.fire_scouted = False

    def _generate_scenario(self):
        # Generate smooth random temperature map spanning across the full 250x100 space
        self.temperature_grid = np.zeros((self.grid_x, self.grid_y), dtype=np.float32)
        num_hotspots = random.randint(5, 9)
        valid_indices = np.argwhere(self.valid_mask)

        if len(valid_indices) > 0:
            hotspots = valid_indices[np.random.choice(len(valid_indices), num_hotspots, replace=False)]
            x_indices, y_indices = np.indices((self.grid_x, self.grid_y))

            for hx, hy in hotspots:
                dist_sq = (x_indices - hx)**2 + (y_indices - hy)**2
                self.temperature_grid += np.exp(-dist_sq / 1200.0)

            min_v, max_v = self.temperature_grid.min(), self.temperature_grid.max()
            if max_v > min_v:
                self.temperature_grid = (self.temperature_grid - min_v) / (max_v - min_v) * 100.0
            else:
                self.temperature_grid.fill(50.0)

        self.temperature_grid[~self.valid_mask] = np.nan

        # Generate fire location near a super hot location (temperature >= 75.0)
        hot_mask = (self.temperature_grid >= 75.0) & self.valid_mask
        hot_indices = np.argwhere(hot_mask)

        if len(hot_indices) == 0:
            hot_indices = valid_indices

        fire_idx = hot_indices[random.randint(0, len(hot_indices) - 1)]
        self.fire_pos = np.array([float(fire_idx[0]), float(fire_idx[1])], dtype=np.float32)
        self.fire_scouted = False

    def reset(self, seed=None, options=None):
        super().reset(seed=seed)
        self.pos = self.start_pos.copy()
        self.steps = 0
        self.battery = 100.0

        # Generate new temperature layout and fire location for this run
        self._generate_scenario()

        self.visited = ~self.valid_mask.copy()
        self.trajectory = [self.pos.copy()]
        self._mark_visited()

        return self._get_obs(), {}

    def _get_obs(self):
        closest_station = min(self.stations, key=lambda s: np.linalg.norm(self.pos - s))
        dist_x = closest_station[0] - self.pos[0]
        dist_y = closest_station[1] - self.pos[1]
        steps_left = self.max_steps - self.steps

        # Read thermal sensor at the drone's current grid position
        x, y = int(self.pos[0]), int(self.pos[1])
        if 0 <= x < self.grid_x and 0 <= y < self.grid_y and self.valid_mask[x, y]:
            current_temp = self.temperature_grid[x, y]
            if np.isnan(current_temp):
                current_temp = 50.0
        else:
            current_temp = 50.0

        return np.array([dist_x, dist_y, steps_left, self.battery, current_temp], dtype=np.float32)

    def _mark_visited(self):
        x, y = int(self.pos[0]), int(self.pos[1])
        r = self.discovery_radius
        new_tiles = 0

        for i in range(max(0, x-r), min(self.grid_x, x+r+1)):
            for j in range(max(0, y-r), min(self.grid_y, y+r+1)):
                if not self.visited[i, j]:
                    self.visited[i, j] = True
                    new_tiles += 1
        return new_tiles

    def step(self, action):
        dx = (action % 3 - 1) * 2.1
        dy = (action // 3 - 1) * 2.1

        proposed_x = self.pos[0] + dx
        proposed_y = self.pos[1] + dy

        if self.boundary_path.contains_point((proposed_x, proposed_y)):
            self.pos[0] = proposed_x
            self.pos[1] = proposed_y

        self.steps += 1
        self.trajectory.append(self.pos.copy())

        self.battery -= (100.0 / self.max_steps)

        reward = 1

        # Check if drone scouted the wildfire within discovery range (+10,000 score booster)
        if not self.fire_scouted:
            dist_to_fire = np.linalg.norm(self.pos - self.fire_pos)
            if dist_to_fire <= self.discovery_radius:
                reward += 10000.0
                self.fire_scouted = True

        distances = [np.linalg.norm(self.pos - station) for station in self.stations]
        min_dist_to_station = min(distances)

        if self.battery <= 20.0 and min_dist_to_station > 9.0:
            reward -= 5.0

        terminated = False
        truncated = False

        if self.steps >= self.max_steps or self.battery <= 0:
            terminated = True
            if min_dist_to_station <= 9.0:
                closest_station_idx = np.argmin(distances)
                if closest_station_idx == 0:
                    reward += 150.0  # Home Station reward
                else:
                    reward += 250.0  # Increased reward for reaching other stations
            else:
                reward -= 100.0  # Stranded penalty

        return self._get_obs(), reward, terminated, truncated, {}

Transition = namedtuple('Transition', ('state', 'action', 'next_state', 'reward'))

class ReplayMemory(object):
    def __init__(self, capacity):
        self.memory = deque([], maxlen=capacity)

    def push(self, *args):
        self.memory.append(Transition(*args))

    def sample(self, batch_size):
        return random.sample(self.memory, batch_size)

    def __len__(self):
        return len(self.memory)

class DQN(nn.Module):
    def __init__(self, n_observations, n_actions):
        super(DQN, self).__init__()
        self.layer1 = nn.Linear(n_observations, 128)
        self.layer2 = nn.Linear(128, 128)
        self.layer3 = nn.Linear(128, n_actions)

    def forward(self, x):
        x = F.relu(self.layer1(x))
        x = F.relu(self.layer2(x))
        return self.layer3(x)

BATCH_SIZE = 128
GAMMA = 0.99
EPS_START = 0.9
EPS_END = 0.05
EPS_DECAY = 10000
TAU = 0.005
LR = 1e-3

env = AreaDiscoveryEnv()
n_actions = env.action_space.n
state, info = env.reset()
n_observations = len(state)

policy_net = DQN(n_observations, n_actions).to(device)
target_net = DQN(n_observations, n_actions).to(device)
target_net.load_state_dict(policy_net.state_dict())

optimizer = optim.AdamW(policy_net.parameters(), lr=LR, amsgrad=True)
memory = ReplayMemory(10000)
steps_done = 0
all_trajectories = [] # To store paths for visualization
episode_rewards = []

def select_action(state):
    global steps_done
    sample = random.random()
    eps_threshold = EPS_END + (EPS_START - EPS_END) * math.exp(-1. * steps_done / EPS_DECAY)
    steps_done += 1
    if sample > eps_threshold:
        with torch.no_grad():
            return policy_net(state).max(1).indices.view(1, 1)
    else:
        return torch.tensor([[env.action_space.sample()]], device=device, dtype=torch.long)

import matplotlib.patches as patches

def plot_trajectories(show_result=False):
    plt.figure(figsize=(10, 4.5))
    plt.clf()

    plt.xlim(0, 250)
    plt.ylim(0, 100)
    plt.gca().set_aspect('equal', adjustable='box')

    # Plot Temperature Grid Heatmap across the full 250x100 grid bounds
    plt.imshow(
        env.temperature_grid.T,
        origin='lower',
        extent=[0, env.grid_x, 0, env.grid_y],
        cmap='YlOrRd',
        alpha=0.6,
        vmin=0,
        vmax=100,
        zorder=1
    )

    path_verts = env.boundary_path.vertices
    plt.plot(path_verts[:, 0], path_verts[:, 1], 'k-', linewidth=2, label="Mountain Boundary", zorder=2)

    # Plot Wildfire Location Marker
    plt.scatter([env.fire_pos[0]], [env.fire_pos[1]], color='darkred', marker='*', s=250, zorder=6, label="Wildfire Location")

    # Plot ALL Ranger Stations on the map distinctly
    for idx, station in enumerate(env.stations):
        if idx == 0:
            plt.scatter([station[0]], [station[1]], color='red', s=100, zorder=5, label="Main Home Station")
        else:
            plt.scatter([station[0]], [station[1]], color='orange', s=100, zorder=5, label="Ranger Stations" if idx == 1 else "")

    for traj in all_trajectories[:-1]:
        traj_arr = np.array(traj)
        plt.plot(traj_arr[:, 0], traj_arr[:, 1], color='gray', alpha=0.3, linewidth=1, zorder=3)

    if len(all_trajectories) > 0:
        latest_traj = np.array(all_trajectories[-1])
        plt.plot(latest_traj[:, 0], latest_traj[:, 1], color='blue', linewidth=2, label="Latest Flight Path", zorder=4)

    plt.xlabel("East-West Distance Units (~0.16 miles / unit)", fontsize=10)
    plt.ylabel("North-South Distance Units (~0.16 miles / unit)", fontsize=10)
    plt.title('Santa Monica Mountains Wildfire Patrol & Thermal Scans', fontsize=12)

    plt.legend(loc='upper right', fontsize=8)
    plt.grid(True, linestyle='--', alpha=0.3)

    if is_ipython:
        display.clear_output(wait=True)
        display.display(plt.gcf())

def optimize_model():
    if len(memory) < BATCH_SIZE:
        return
    transitions = memory.sample(BATCH_SIZE)
    batch = Transition(*zip(*transitions))

    non_final_mask = torch.tensor(tuple(map(lambda s: s is not None, batch.next_state)), device=device, dtype=torch.bool)
    non_final_next_states = torch.cat([s for s in batch.next_state if s is not None])
    state_batch = torch.cat(batch.state)
    action_batch = torch.cat(batch.action)
    reward_batch = torch.cat(batch.reward)

    state_action_values = policy_net(state_batch).gather(1, action_batch)

    next_state_values = torch.zeros(BATCH_SIZE, device=device)
    with torch.no_grad():
        next_state_values[non_final_mask] = target_net(non_final_next_states).max(1).values

    expected_state_action_values = (next_state_values * GAMMA) + reward_batch

    criterion = nn.SmoothL1Loss()
    loss = criterion(state_action_values, expected_state_action_values.unsqueeze(1))

    optimizer.zero_grad()
    loss.backward()
    torch.nn.utils.clip_grad_value_(policy_net.parameters(), 100)
    optimizer.step()

num_episodes = 6000 if torch.cuda.is_available() else 300

for i_episode in range(num_episodes):
    state, info = env.reset()
    state = torch.tensor(state, dtype=torch.float32, device=device).unsqueeze(0)

    ep_reward = 0
    for t in count():
        action = select_action(state)
        observation, reward, terminated, truncated, _ = env.step(action.item())
        ep_reward += reward
        reward_tensor = torch.tensor([reward], device=device, dtype=torch.float32)
        done = terminated or truncated

        if terminated:
            next_state = None
        else:
            next_state = torch.tensor(observation, dtype=torch.float32, device=device).unsqueeze(0)

        memory.push(state, action, next_state, reward_tensor)
        state = next_state

        optimize_model()

        # Soft update target network
        target_net_state_dict = target_net.state_dict()
        policy_net_state_dict = policy_net.state_dict()
        for key in policy_net_state_dict:
            target_net_state_dict[key] = policy_net_state_dict[key]*TAU + target_net_state_dict[key]*(1-TAU)
        target_net.load_state_dict(target_net_state_dict)

        if done:
            all_trajectories.append(env.trajectory)
            episode_rewards.append(ep_reward)

            # Update visualization every 20 episodes to save rendering time
            if (i_episode + 1) % 20 == 0:
                plot_trajectories()
            break

print('Training Complete')
plot_trajectories(show_result=True)
plt.ioff()
plt.show()

# Optional: Plot the learning curve
plt.figure(2)
plt.plot(episode_rewards)
plt.title('Reward over Time')
plt.xlabel('Episode')
plt.ylabel('Total Reward')
plt.show()